<?php $currentCategory = Mage::getSingleton('blog/cat');?>
<div class="block block-blog blog-menu">
    <div class="block-content">
    	<?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
            <div class="menu-categories menu-block-sub">
                <h5><?php echo Mage::helper('blog')->__('Categories'); ?></h5>
                <ul>
                    <?php $cats = $this->getCategories(); ?>
                    <?php foreach ($cats as $cat): ?>
                        <li class="<?php if($cat->getId() == $currentCategory->getId()) echo 'active'; ?>"><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php if ($posts = $this->getRecent()): ?>
            <div class="menu-recent menu-block-sub">
                <h5><?php echo Mage::helper('blog')->__('Recent Posts'); ?></h5>
                <ul>
                    <?php foreach ($posts as $post): ?>
                        <li><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php if($dateRangeArray = $this->getDateRange()) : 
            $countRange = 3;
            $iLi = 0;
            $checkFirst = false;
        ?>
            <div class="menu-archives menu-block-sub">
                <h5><?php echo Mage::helper('blog')->__('Archives'); ?></h5>
                <ul class="archive-list-menu">
                    <?php foreach ($dateRangeArray as $year => $dateRange): ?>
                        <?php if($checkFirst) break; ?>
                        <?php foreach ($dateRange as $month): 
                            $iLi++;
                            if($iLi>$countRange){
                                $checkFirst = true;
                                break;
                            }
                            ?>
                            <li><a href="<?php echo $this->getUrl('blog/archive',array('date'=>$year.'-'.$month));?>" ><?php echo $this->getFrontDateMonth($month) . ' ' . $year; ?></a></li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ul>
                <?php if($iLi>$countRange): ?>
                    <ul class="block-click-more">
                        <li class="more menu-archives-more" data-count="1"><a href="#"><?php echo $this->__('More...'); ?></li></a>
                    </ul>
                <?php endif; ?>
            </div>
            <script type="text/javascript">
                jQuery(document).ready(function($) {
                    var arrayListArchive = [];
                    <?php 
                    $iLi = 0;
                    $stringli = '';
                    foreach ($dateRangeArray as $year => $dateRange){
                        foreach ($dateRange as $month){
                            $iLi++;
                            if($iLi > $countRange) {
                                if($iLi > ($countRange + 1) && $iLi%$countRange==1) { ?>
                                    arrayListArchive.push('<?php echo $stringli; ?>');
                                <?php 
                                    $stringli = '';
                                }
                                $stringli .= '<li><a href="'.$this->getUrl('blog/archive',array('date'=>$year.'-'.$month)).'">'.$this->getFrontDateMonth($month) . ' ' . $year.'</a></li>';
                            }
                        }
                    }
                    if($stringli) { ?>
                        arrayListArchive.push('<?php echo $stringli; ?>');
                    <?php }
                    ?>
                    if(arrayListArchive.length > 0) {
                        var lengthListArchive = arrayListArchive.length;
                        $(document).on('click','.menu-archives-more',function() {
                            count = $(this).data('count');
                            $('ul.archive-list-menu').append(arrayListArchive[count-1]);
                            $(this).data('count',(count+1));
                            if((count+1) > lengthListArchive) {
                                $(this).remove();
                                return false;
                            }
                            return false;
                        });
                    }
                });
            </script>
        <?php endif; ?>
        <?php echo $this->getChildHtml('blog_tags'); ?>
    </div>
</div>