<?php $posts = $this->getPosts();
if(!count($posts)) {
    return;
}
$suffix = md5(microtime() . mt_rand());
$_columnCount = $this->getColumnCount() ? $this->getColumnCount() : 3;
$_bHelper = $this->helper('blog');
$_blogRoute = $_bHelper->getRoute();
$_width = 240;
?>

<div class="post-list-slider">
    <h3 class="pl-title"><?php echo $this->__('Latest News'); ?></h3>
    <a href="<?php echo $_blogRoute; ?>" class="link link-view-all">
        <span><?php echo $this->__('View All'); ?></span>
    </a>
    <div class="post-list-slier-outer">
        <div class="bx-container-controller">
            <span class="bx-prev bx-prev-<?php echo $suffix; ?>"></span>
            <span class="bx-next bx-next-<?php echo $suffix; ?>"></span>
        </div>
        <div class="bxslider bxslider-<?php echo $suffix; ?>">
            <?php foreach ($posts as $post): ?>
                <div class="post-item">
                    <div class="post-image">
                        <?php if ($post->getThumbnail() || $post->getImage()) : ?>
                            <a href="<?php echo $post->getAddress(); ?>">
                                <?php if ($post->getThumbnail()) : ?>
                                    <img src="<?php echo $this->helper('blog')->getImageUrl($post->getThumbnail()); ?>" />
                                <?php elseif ($post->getImage()) : ?>
                                    <img src="<?php echo $this->helper('blog')->getImageUrl($post->getImage()); ?>" />
                                <?php endif ?>
                            </a>
                        <?php endif ?>
                    </div>
                    <div class="post-title">
                        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                    </div>
                    <div class="post-short-content">
                        <?php echo substr(strip_tags($post->getData('short_content')),0,100); ?>
                    </div>
                    <div class="post-read-more">
                        <a href="<?php echo $post->getAddress(); ?>" class="link linkl-read-more">
                            <span><?php echo $this->__('Read More'); ?></span>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($) {
    $('.bxslider-<?php echo $suffix; ?>').bxSlider({
        mode: 'horizontal',
        speed: 500,
        infiniteLoop: true,
        auto: false,
        pause: 4000,
        moveSlides: 1,
        slideMargin: 5,
        slideWidth: <?php echo $_width; ?>,
        minSlides: 1,
        maxSlides: <?php echo $_columnCount; ?>,
        nextSelector: '.bx-next-<?php echo $suffix; ?>',
        prevSelector: '.bx-prev-<?php echo $suffix; ?>',
        pager: false,
        onSlideAfter: function(slideElement, oldIndex, newIndex){
            $('.bxslider-<?php echo $suffix; ?> >li').removeClass('active');
            $('.bxslider-<?php echo $suffix; ?> >li').eq(newIndex + 1).addClass('active');
        }
    });
});
//]]>
</script>