<script>
jQuery(document).ready(function($) {
    function checkedActiveInput(dom)
    {
        if(dom.length > 0) {
            dom.each(function(i,k) {
                if($(this).is(':checked')) {
                    $(this).addClass('active');
                }
                else {
                    $(this).removeClass('active');
                }
            });
        }
    }
    checkedActiveInput($('input[type=radio]'));
    checkedActiveInput($('input[type=checkbox]'));
    $(document).on('change','input[type=radio]',function() {
        $(this).siblings('input[type=radio]').removeClass('active');
        $(this).parent().siblings().find('input[type=radio]').removeClass('active');
        if($(this).is(':checked')) {
            $(this).addClass('active');
        }
    });
    $(document).on('change','input[type=checkbox]',function() {
        if($(this).is(':checked')) {
            $(this).addClass('active');
        }
        else {
            $(this).removeClass('active');
        }
    });
});
</script>
