<div class="ft-block">
	<div class="ftb-title collapse-title expand">
		<span>Company Information</span>
	</div>
	<ul class="ftb-content collapse-content">
		<li>
			<a href="{{store url="about-us"}}">About Us</a>
		</li>
		<li>
			<a href="{{store url="careers"}}">Careers</a>
		</li>
		<li>
			<a href="{{store url="corporate-social-responsibility"}}">Corporate Social Responsibility</a>
		</li>
		<li>
			<a href="{{store url="inclusion-diversity"}}">Inclusion & Diversity</a>
		</li>
		<li>
			<a href="{{store url="how-to-become-a-supplier"}}">How to become a supplier</a>
		</li>
		<li>
			<a href="{{store url="investor-relations"}}">Investor Relations</a>
		</li>
		<li>
			<a href="{{store url="press-room"}}">Press Room</a>
		</li>
		<li>
			<a href="{{store url="supplier-overview"}}">Supplier Overview</a>
		</li>
		<li>
			<a href="{{store url="technical-education"}}">Technical Education</a>
		</li>
		<li>
			<a href="{{store url="landing"}}">Worldwide</a>
		</li>
	</ul>
</div>
<div class="ft-block">
	<div class="ftb-title collapse-title expand">
		<span>Customer Support</span>
	</div>
	<ul class="ftb-content collapse-content">
		<li>
			<a href="{{store url="catalog-request"}}">
				<span class="ic-cs"><img src="{{skin url="images/icon-catalogi.png"}}" alt="" /></span>
				<span>Catalog Request</span>
			</a>
		</li>
		<li>
			<a href="{{store url="contact-us"}}">
				<span class="ic-cs"><img src="{{skin url="images/icon-contact-us.png"}}" alt="" /></span>
				<span>Contact us</span>
			</a>
		</li>
		<li>
			<a href="{{store url="feedback"}}">
				<span class="ic-cs"><img src="{{skin url="images/icon-feedback.png"}}" alt="" /></span>
				<span>Feedback</span>
			</a>
		</li>
		<li>
			<a href="{{store url="find-a-branch"}}">
				<span class="ic-cs"><img src="{{skin url="images/icon-find-a-band.png"}}" alt="" /></span>
				<span>Find a Branch</span>
			</a>
		</li>
	</ul>
</div>
<div class="ft-block">
	<div class="ftb-title collapse-title expand">
		<span>Order Support</span>
	</div>
	<ul class="ftb-content collapse-content">
		<li>
			<a href="{{store url="orders"}}">Orders</a>
		</li>
		<li>
			<a href="{{store url="pick-up"}}">Pick-up</a>
		</li>
		<li>
			<a href="{{store url="returns"}}">Returns</a>
		</li>
		<li>
			<a href="{{store url="shippingand-delivery"}}">Shipping and Delivery</a>
		</li>
	</ul>
</div>
<div class="ft-block">
	<div class="ftb-title collapse-title expand">
		<span>Online Resources</span>
	</div>
	<ul class="ftb-content collapse-content">
		<li>
			<a href="{{store url="clearance-center"}}">Clearance Center</a>
		</li>
		<li>
			<a href="{{store url="hot-buys"}}">Hot Buys</a>
		</li>
		<li>
			<a href="{{store url="rebates"}}">Rebates</a>
		</li>
		<li>
			<a href="{{store url="repair-parts"}}">Repair Parts</a>
		</li>
		<li>
			<a href="{{store url="site-features"}}">Site Features</a>
		</li>
		<li>
			<a href="{{store url="supply-link"}}">Supply Link</a>
		</li>
		<li>
			<a href="{{store url="today-features"}}">Today’s Features</a>
		</li>
	</ul>
</div>
<div class="ft-block">
	<div class="ftb-title collapse-title expand">
		<span>Services</span>
	</div>
	<ul class="ftb-content collapse-content">
		<li>
			<a href="{{store url="auto-reorder"}}">Auto-Reorder</a>
		</li>
		<li>
			<a href="{{store url="catalog"}}">Catalog</a>
		</li>
		<li>
			<a href="{{store url="special-orders"}}">Special Orders</a>
		</li>
		<li>
			<a href="{{store url="emergency-services"}}">Emergency Services</a>
		</li>
		<li>
			<a href="{{store url="inventory-management"}}">Inventory Management</a>
		</li>
		<li>
			<a href="{{store url="invoices-your-way"}}">Invoices your Way</a>
		</li>
		<li>
			<a href="{{store url="online-purchasing-solutions"}}">Online Purchasing Solutions</a>
		</li>
	</ul>
</div>
