<div class="fl-box">
	<h3 class="ec-label collapse-title expand">
		<span>Sitemap</span>
	</h3>
	<ul class="ec-box collapse-content">
		<li>
			<a href="{{store url=""}}">Home</a>
		</li>
		<li>
			<a href="{{store url="about-us"}}">About Us</a>
		</li>
		<li>
			<a href="{{store url="beauty.html"}}">Beauty</a>
		</li>
		<li>
			<a href="{{store url="travel.html"}}">Travel</a>
		</li>
		<li>
			<a href="{{store url="omiyage.html"}}">Omiyage</a>
		</li>
		<li>
			<a href="{{store url="contact-us.html"}}">Contact Us</a>
		</li>
	</ul>
</div>
