<?php $item = $this->getBanner(); ?>
<?php if (is_object($item)) : ?>
    <?php $_helper = $this->helper('icycle'); ?>
    <?php $_iHelper = $this->helper('icycle/image'); ?>
    <?php $suffix = md5(microtime() . mt_rand()) ?>
    <?php $_imageList = $item->getImageListForFrontend(); ?>
    <?php if (is_array($_imageList) and sizeof($_imageList) > 0) : ?>
        <?php
            $w = (int) $item->getExtraOption('width') ? $item->getExtraOption('width') : 100;
            $h = (int) $item->getExtraOption('height') ? $item->getExtraOption('height') : 75;
            $width = $item->getWidth();
            $height = $item->getHeight();
            //echo $w.' -- ' . $h . ' -- ' . $width . ' -- ' . $height;
        ?>
        <div class="bxslider-wrapper icycle-slider">
            <div class="bx-container-controller icycle-controller">
                <span class="bx-prev bx-prev-<?php echo $suffix; ?>"></span>
                <span class="bx-next bx-next-<?php echo $suffix; ?>"></span>
            </div>
            <ul class="bxslider bxslider-<?php echo $suffix; ?>">
                <?php foreach ($_imageList as &$_item): ?>
                    <?php if ( $size = $_helper->getThumbSize($_item['file'], $width, $height) ) : ?>
                        <?php $thumb = $_iHelper->init($_item['file'])->resize($size->getWidth(), $size->getHeight()); ?>
                        <li class="item">
                            <div class="item-image-outer"><div class="item-image-inner">
                                <img src="<?php echo $thumb; ?>" />
                                <?php if (isset($_item['description'][0])) : ?>
                                    <div class="icycle-description"><?php echo $_helper->parseText($_item['description']); ?></div>
                                <?php endif; ?>
                            </div></div>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    <script type="text/javascript">
            //<![CDATA[
            jQuery(document).ready(function($) {
                var bxslider_<?php echo $suffix; ?> = $('.bxslider-<?php echo $suffix; ?>').bxSlider({
                    mode: 'horizontal',
                    speed: 500,
                    infiniteLoop: true,
                    auto: false,
                    pause: 4000,
                    moveSlides: 1,
                    slideMargin: 0,
                    slideWidth: <?php echo $width; ?>,
                    minSlides: 1,
                    maxSlides: 1,
                    controls: <?php echo $item->getExtraOption('navigation') ?>,
                    nextSelector: '.bx-next-<?php echo $suffix; ?>',
                    prevSelector: '.bx-prev-<?php echo $suffix; ?>',
                    pager: <?php echo $item->getExtraOption('pagination') ?>
                });
                $(window).resize(function(e) {
                    e.preventDefault();
                    bxslider_<?php echo $suffix; ?>.reloadSlider({
                        mode: 'horizontal',
                        speed: 500,
                        infiniteLoop: true,
                        auto: false,
                        pause: 4000,
                        moveSlides: 1,
                        slideMargin: 0,
                        slideWidth: <?php echo $width; ?>,
                        minSlides: 1,
                        maxSlides: 1,
                        controls: <?php echo $item->getExtraOption('navigation') ?>,
                        nextSelector: '.bx-next-<?php echo $suffix; ?>',
                        prevSelector: '.bx-prev-<?php echo $suffix; ?>',
                        pager: <?php echo $item->getExtraOption('pagination') ?>,
                    });
                });
            });
            //]]>
            </script>
    <?php endif; ?>
<?php endif; ?>
