<style>
.product-view .product-img-box { float:left; width:100%; padding:0; }
.col3-layout .product-view .product-img-box { float:none; margin:0 auto; }
.product-view .product-img-box .product-image { margin:0 0 25px; border: 0; padding:0; position: relative; min-height: 425px; max-height: 550px;}

.product-view .product-img-box .product-image-zoom { position:relative; width:265px; height:265px; overflow:hidden; z-index:9; }
.product-view .product-img-box .product-image-zoom img { position:absolute; left:0; top:0; cursor:move; }
.product-view .product-img-box .zoom-notice { font-size:11px; margin:0 0 5px; text-align:center; }
.product-view .product-img-box .zoom { position:relative; z-index:9; height:18px; margin:0 auto 13px; padding:0 28px; background:url(../images/slider_bg.gif) 50% 50% no-repeat; cursor:pointer; }
.product-view .product-img-box .zoom.disabled { -moz-opacity:.3; -webkit-opacity:.3; -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=30)";/*IE8*/ opacity:.3; }
.product-view .product-img-box .zoom #track { position:relative; height:18px; }
.product-view .product-img-box .zoom #handle { position:absolute; left:0; top:-1px; width:9px; height:22px; background:url(../images/magnifier_handle.gif) 0 0 no-repeat;  }
.product-view .product-img-box .zoom .btn-zoom-out { position:absolute; left:2px; top:0; }
.product-view .product-img-box .zoom .btn-zoom-in { position:absolute; right:2px; top:0; }
.product-view .product-img-box .more-views h2 { font-size:11px; border-bottom:1px solid #ccc; margin:0 0 8px; text-transform:uppercase; }

.product-view .product-img-box .more-views li { float:left; margin:0 0 8px 9px; }
.product-view .product-img-box .more-views li a { float:left; width:56px; height:56px; border:2px solid #ddd; overflow:hidden; }

.product-image-popup { margin:0 auto; }
.product-image-popup .buttons-set { float:right; clear:none; border:0; margin:0; padding:0; }
.product-image-popup .nav { font-weight:bold; margin:0 100px; text-align:center; }
.product-image-popup .image { display:block; margin:10px 0;  }
.product-image-popup .image-label { font-size:13px; font-weight:bold; margin:0 0 10px; color:#2f2f2f; }
.product-img-box .product-image:after {
    content: "";
    display: block;
    clear: both;
}
.product-img-box .swiper-container.gallery-thumbs{
    width: 55px;
    float: left;
    height: auto !important;
    position: absolute;
    top: 75px;
    left: 0;
    height: 320px !important;
}
.product-img-box .swiper-container.gallery-thumbs .swiper-wrapper{
    top: 40px;
}
.product-img-box .swiper-container.gallery-thumbs .swiper-slide{
    border: 1px solid #e0e0e0;
    background-position: center;
    background-repeat: no-repeat;
    background-size: 100%;
    cursor: pointer;
}
.product-img-box .swiper-container.gallery-thumbs .swiper-slide.swiper-slide-active{
    border: 2px solid #cc4342;
}


.product-img-box .swiper-include {
    width: 392px;
    float: right;
    height: 100%;
    border: 1px solid #e7e7e7;
    padding: 5px 20px;
    position: relative;
}
.product-img-box .swiper-include .swiper-slide{
    background:none !important;
}
.product-img-box .swiper-include .swiper-container.gallery-top{
    width: 100% !important;
    height: 100% !important;
    overflow: hidden;
}
.swiper-button-next.swiper-button-white{
    background: url(../images/icon-next-preview-idv.png) bottom 7px center no-repeat !important;
}
.swiper-button-prev.swiper-button-white {
    background: url(../images/icon-next-preview-idv.png) top 5px center no-repeat !important;
}
</style>
<?php
/**project iten
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
    $_product = $this->getProduct();
    $_galleryImage = $this->getGalleryImages();
    if(!count($_galleryImage)) {
        return;
    }
    $_helper = $this->helper('catalog/output');
    $_iHelper = $this->helper('catalog/image');
    $_zHelper = $this->helper('izoom');
    $suffix = md5(microtime() . mt_rand());
    $m = $_zHelper->getImageSizeByProduct($_product->getId(), 'image', 'width');
    $_widthBig = $m->getWidth();
    $_heightBig = $m->getHeight();
    $_widthSmaill = Mage::getStoreConfig('izoom/general/thumbnail_width');
    $_heightSmaill = Mage::getStoreConfig('izoom/general/thumbnail_height');
?>
<div class="product-image">
    <div class="swiper-container gallery-thumbs swipper-thumbs-<?php echo $suffix; ?>" style="width: <?php echo $_widthSmaill; ?>px;height: <?php echo $_heightSmaill; ?>px;">
        <div class="swiper-wrapper">
            <?php foreach($_galleryImage as $_image): ?>
                <?php if (file_exists($_image->getPath())) : ?>
                    <div class="swiper-slide" style="background-image:url(<?php echo $_iHelper->init($_product, 'image', $_image->getFile()); ?>)">
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="swiper-container gallery-top gallery-top-<?php echo $suffix; ?>" style="width: <?php echo $_widthBig; ?>px;height: <?php echo $_heightBig; ?>px;">
        <div class="swiper-wrapper">
            <?php $i=0; ?>
            <?php foreach($_galleryImage as $_image): ?>
                <?php if (file_exists($_image->getPath())): $i++; ?>
                    <div class="swiper-slide colorbox-product-image" style="background-image:url(<?php echo $_iHelper->init($_product, 'image', $_image->getFile()); ?>)" href="<?php echo $_iHelper->init($_product, 'image', $_image->getFile()); ?>">
                        <a href="<?php echo $_iHelper->init($_product, 'image', $_image->getFile()); ?>" class="cloud-zoom cloud-zoom-<?php echo $i; ?>" rel="zoomWidth:'<?php echo $_zHelper->getZoomConfig('zoom_width') ?>', zoomHeight:'<?php echo $_zHelper->getZoomConfig('zoom_height') ?>', lensWidth:'<?php echo $_zHelper->getZoomConfig('lens_width') ?>', lensHeight:'<?php echo $_zHelper->getZoomConfig('lens_height') ?>', border:<?php echo (int)$_zHelper->getZoomConfig('border') ?>, position:'<?php echo $_zHelper->getZoomConfig('position') ?>', showTitle:<?php echo $_zHelper->getZoomConfig('show_title') ?>, adjustX:10, adjustY:-4, eventHandler:'<?php echo $_zHelper->getZoomConfig('event_handler') ?>'">
                            <img id="image" src="<?php echo $_iHelper->init($_product, 'image', $_image->getFile())->resize($m->getWidth(), $m->getHeight()) ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel()) ?>" />
                        </a>
                    </div>
                    <script type="text/javascript">
                        jQuery(document).ready(function($) {
                            jQuery('.cloud-zoom-<?php echo $i; ?>').CloudZoom();
                        });
                    </script>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
        <!-- Add Arrows -->
        <div class="swiper-button-next swiper-button-white swiper-next-<?php echo $suffix; ?>"></div>
        <div class="swiper-button-prev swiper-button-white swiper-prev-<?php echo $suffix; ?>"></div>
    </div>
</div>


<script>
    jQuery(document).ready(function($) {
        <?php
        $width    = $_zHelper->getDialogConfig('width');
        $maxWidth = $_zHelper->getDialogConfig('max_width');
        $height    = $_zHelper->getDialogConfig('height');
        $maxHeight = $_zHelper->getDialogConfig('max_height');
        ?>
        $(".colorbox-product-image").colorbox({
            rel: 'color-box',
            opacity: 0.5,
            speed: <?php echo (int) $_zHelper->getDialogConfig('speed') ?>,
            current: '{current} / {total}',

            <?php if (strpos($width, 'false') === false) : ?>
            width: '<?php echo $width ?>',
            <?php endif; ?>
            <?php if (strpos($maxWidth, 'false') === false) : ?>
            maxWidth: '<?php echo $maxWidth ?>',
            <?php endif; ?>

            <?php if (strpos($height, 'false') === false) : ?>
            height: '<?php echo $height ?>',
            <?php endif; ?>
            <?php if (strpos($maxHeight, 'false') === false) : ?>
            maxHeight: '<?php echo $maxHeight ?>',
            <?php endif; ?>

            fixed: <?php echo $_zHelper->getDialogConfig('fixed') ?>,
            className: 'zoom'
        });
    });
    var galleryTop = new Swiper('.gallery-top-<?php echo $suffix; ?>', {
        nextButton: '.swiper-next-<?php echo $suffix; ?>',
        prevButton: '.swiper-prev-<?php echo $suffix; ?>',
        spaceBetween: 10,
        loop:true,
        loopedSlides: 5, //looped slides should be the same
    });
    var galleryThumbs = new Swiper('.swipper-thumbs-<?php echo $suffix; ?>', {
        spaceBetween: 10,
        slidesPerView: 4,
        touchRatio: 0.2,
        loop:true,
        loopedSlides: 5, //looped slides should be the same
        slideToClickedSlide: true,
        direction: 'vertical',
        centeredSlides: true,
    });
    galleryTop.params.control = galleryThumbs;
    galleryThumbs.params.control = galleryTop;
</script>
