<?php $item = $this->getBanner(); ?>
<?php if (is_object($item)) : ?>
    <?php $_helper = $this->helper('icycle'); ?>
    <?php $_iHelper = $this->helper('icycle/image'); ?>
    <?php $class = md5(microtime() . mt_rand()) ?>
    <?php $_imageList = $item->getImageListForFrontend(); ?>
    <?php if (is_array($_imageList) and sizeof($_imageList) > 0) : ?>
        <div class="bxslider-wrapper">
            <div class="bxslider bxslider-<?php echo $class; ?>">
                <?php $i=0; foreach ($_imageList as &$_item) : $i++; ?>
                    <?php if($i%$_columnCountSlider==1) : ?>
                        <div class="slide">
                    <?php endif; ?>
                    <?php 
                    if($bannerUrl = $_helper->parseText($_item['link'])) {
                    }
                    else {
                        $bannerUrl = '#';
                    }
                    ?>
                    <div class="slide">
                        <div class="product-image-inner">
                            <a href="<?php echo $bannerUrl; ?>" class="brand-image">
                                <img src="<?php echo $_helper->getImageUrl($_item['file']); ?>">
                            </a>
                            <div class="product-view-details">
                                <a href="<?php echo $bannerUrl; ?>">
                                    <span class="ico-product-view-details"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <script type="text/javascript">
        jQuery(document).ready(function($){
            $('.bxslider-<?php echo $class; ?>').bxSlider({
                minSlides: <?php echo $item->getExtraOption('cols'); ?>,
                maxSlides: <?php echo $item->getExtraOption('cols'); ?>,
                slideWidth: 170,
                slideMargin: 20,
                pager: <?php echo $item->getExtraOption('pagination'); ?>,
                auto: <?php if($item->getExtraOption('time')) echo 'true'; else echo 'false'; ?>,
                pause: <?php echo $item->getExtraOption('time'); ?>
            });
        });
    </script>
    <?php endif; ?>
<?php endif; ?>