<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $_iHelper = $this->helper('catalog/image');
    $_zHelper = $this->helper('izoom');
    //width = 530x650 - slider 130x150
?>
<?php $suffix = md5(microtime() . mt_rand()) ?>
<?php $m = $_zHelper->getImageSizeByProduct($_product->getId(), 'image', 'width'); ?>
<div class="product-image-wrapper">
    <?php if ($_zHelper->getZoomConfig('show_thumb') == "1") : ?>
        <?php if (count($this->getGalleryImages()) > 0): ?>
            <?php $maxSlides =  (int) $_zHelper->getSliderConfig('number_default') ?>
            <div class="more-views-gallery">
                <?php //if (count($this->getGalleryImages()) > $maxSlides): ?>
                <div class="slider-nav-container">
                    <span id="slider-prev-<?php echo $suffix ?>" class="slider-prev"></span>
                    <span id="slider-next-<?php echo $suffix ?>" class="slider-next"></span>
                </div>
                <?php //endif ?>
                <div id="izoom_slider_container">
                    <ul id="izoom_slider" class="bxslider">
                    <?php foreach ($this->getGalleryImages() as $_image): ?>
                        <?php if (file_exists($_image->getPath())) : ?>
                            <?php $_mImage = $_zHelper->getImageSize($_image); ?>
                            <?php $_tImage = $_zHelper->getThumbnailSize($_image); ?>
                            <li class="gallery-item" data-image-big="<?php echo $_iHelper->init($_product, 'image', $_image->getFile()); ?>">
                                <a href="#" data-image="<?php echo $_iHelper->init($this->getProduct(), 'small_image', $_image->getFile())->resize($m->getWidth(), $m->getHeight()); ?>" data-zoom-image="<?php echo $_iHelper->init($_product, 'image', $_image->getFile()); ?>" class="link-colorbox-gallery" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                                    <img src="<?php echo $_iHelper->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_tImage->getWidth(), $_tImage->getHeight()); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </ul>
                </div>
            </div>
            <?php //if (count($this->getGalleryImages()) > $maxSlides): ?>
            <script type="text/javascript">
            //<![CDATA[
            var slider_<?php echo $suffix ?>;
            jQuery(function($) {
                slider_<?php echo $suffix ?> = $('#izoom_slider').bxSlider({
                    mode: '<?php echo $_zHelper->getSliderConfig('mode') ?>',
                    speed: <?php echo (int) $_zHelper->getSliderConfig('speed') ?>,
                    infiniteLoop: <?php echo $_zHelper->getSliderConfig('infinite_loop') ?>,
                    auto: <?php echo $_zHelper->getSliderConfig('auto') ?>,
                    pause: <?php echo (int) $_zHelper->getSliderConfig('pause') ?>,
                    moveSlides: <?php echo (int) $_zHelper->getSliderConfig('move_slides') ?>,
                    slideMargin: <?php echo (int) $_zHelper->getSliderConfig('slide_margin') ?>,
                    slideWidth: <?php echo (int) $_zHelper->getSliderConfig('width_default') ?>,
                    minSlides: <?php echo (int) $_zHelper->getSliderConfig('number_default') ?>,
                    maxSlides: <?php echo (int) $_zHelper->getSliderConfig('number_default') ?>,
                    nextSelector: '#slider-next-<?php echo $suffix ?>',
                    prevSelector: '#slider-prev-<?php echo $suffix ?>',
                    pager: false
                });
            });
            //]]>
            </script>
            <?php //endif ?>
        <?php endif; ?>
    <?php endif; ?>
    <div class="product-image">
        <div class="pi-inner" style="width: <?php echo $m->getWidth() ?>px; margin: 0 auto;">
            <a href="<?php echo $_iHelper->init($_product, 'image'); ?>" class="link-colorbox-product-image">
                <img id="image" src="<?php echo $_iHelper->init($_product, 'image')->resize($m->getWidth(), $m->getHeight()) ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel()) ?>" data-zoom-image="<?php echo $_iHelper->init($_product, 'image'); ?>" />
            </a>
            <?php /*if ($_zHelper->enableDialog()) : ?>
            <a title="<?php echo $this->__('Zoom') ?>" href="<?php echo $_iHelper->init($_product, 'image'); ?>" class="color-box zoom-button" id="zoom_button"><?php echo $this->__('Zoom') ?></a>
            <?php endif;*/ ?>
        </div>
    </div>
</div>
<?php if ($_zHelper->enableDialog()) : ?>
<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($) {
    <?php $width    = $_zHelper->getDialogConfig('width') ?>
    <?php $maxWidth = $_zHelper->getDialogConfig('max_width') ?>
    <?php $height    = $_zHelper->getDialogConfig('height') ?>
    <?php $maxHeight = $_zHelper->getDialogConfig('max_height') ?>
    $(".cloud-zoom-gallery").first().removeClass("cboxElement");
    var elevateZoomProduct = $('#image').elevateZoom({
        responsive: true,
        imageCrossfade: true,
        cursor: "crosshair",
        loadingIcon: '<?php echo $this->getSkinUrl('VS/images/opc-ajax-loader.gif'); ?>',
        gallery:'izoom_slider_container',
        galleryActiveClass: 'active',
        scrollZoom: true
   });
    $(document).on('click','.link-colorbox-product-image',function(event) {
        event.preventDefault();
        hrefColorbox = $(this).find('img').attr('data-zoom-image');
        $.colorbox({
            href: hrefColorbox,
            className: 'colorbox-product-image',
        });
    });
    $('.link-colorbox-gallery').click(function(event){
        hrefColorbox = $(this).attr('data-zoom-image');
        $('.link-colorbox-product-image').find('img').attr('data-zoom-image',hrefColorbox);
    });
});
//]]>
</script>
<?php endif; ?>