<style>
.popup-wrapper {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0,0,0,0.7);
    opacity: 0;
    visibility: hidden;
    z-index: 9999;
}
.popup-wrapper.active {
    opacity: 1;
    visibility: visible;
}
.popup-container {
    position: absolute;
    width: 610px;
    max-width: 90%;
    height: 4000px;
    max-height: 90%;
    margin: auto;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    vertical-align: middle;
    background: #fff;
    font-size: 16px;
    color: #5f594b;
    overflow: overlay;
    overflow-x: hidden;
}
.popup-outer {
    overflow: overlay;
    overflow-x: hidden;
    width: 100%;
    height: 100%;
    padding: 20px;
}
.popup-container .popup-close-btn a {
    position: absolute;
    top: -20px;
    right: -15px;
    background: url(../images/icon-close-popup.png) center no-repeat;
    font-size: 0;
    width: 34px;
    height: 34px;
}
.popup-container .popup-inner h3{
    text-align: center;
}
</style>

<div class="popup-wrapper popup-video">
    <div class="popup-container">
        <div class="popup-close-btn">
            <a href="#">Close</a>
        </div>
        <div class="popup-outer">
            <div class="popup-inner">
                <?php echo $_video; ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function($) {
      $(window).load(function(event) {
            setTimeout(function() {
                $('.popup-wrapper').addClass('active');
            },1000);
        });
        $(document).on('click','.link-popup',function(event) {
            event.preventDefault();
            $(this).siblings('.popup-wrapper').fadeIn(500);
        });
        $(document).on('click','.popup-close-btn a',function(event) {
            event.preventDefault();
            $('.popup-wrapper').fadeOut(500);
        });

        $(window).load(function(event) {
            setTimeout(function() {
                $('.popup-wrapper.popup-subscribe').addClass('active');
            },1000);
        });
        $(document).on('click','.popup-close-btn a',function(event) {
            event.preventDefault();
            $('.popup-wrapper').removeClass('active');
        });
    });
</script>
