<?php
$_product = $this->getProduct();
$arrayViewed = Mage::getSingleton('core/session')->getData('product_viewed_customer');
if(!$arrayViewed) {
    $arrayViewed = array();
}
$_productId = $_product->getId();
if(in_array($_productId, $arrayViewed)) {
    $keyId = array_search($_productId, $arrayViewed);
    unset($arrayViewed[$keyId]);
    //unset($_productId);
}
array_unshift($arrayViewed,$_productId);
$arrayViewed = array_slice($arrayViewed,0,5);
Mage::getSingleton('core/session')->setData('product_viewed_customer',$arrayViewed);



$arrayViewed = Mage::getSingleton('core/session')->getData('product_viewed_customer');
if(!count($arrayViewed)) {
    return;
}
$_currentProduct = Mage::registry('current_product');
if($_currentProduct && $_currentProduct->getId()) {
    $keyId = array_search($_currentProduct->getId(), $arrayViewed);
    unset($arrayViewed[$keyId]);
}
if(!count($arrayViewed)) {
    return;
}
$_products = Mage::getModel('catalog/product')->getCollection()
    //->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes())
    //->addMinimalPrice()->addFinalPrice()->addTaxPercents()
    ->addAttributeToFilter('entity_id',array('in'=>$arrayViewed));

    //->addUrlRewrite($this->getCurrentCategory()->getId());
Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($_products);
Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($_products);
if(!count($_products)) {
    return ;
}