	<div class="product-collateral">
                <ul class="tabs">
                    <li id="product_tabs_1" class="active first"><a href="#"><?php echo $this->__('Details'); ?></a></li>
                    <li id="product_tabs_2" ><a href="#"><?php echo $this->__('Product Info'); ?></a></li>
                    <li id="product_tabs_3" ><a href="#"><?php echo $this->__('Legal Disclaimer'); ?></a></li>
                    <li id="product_tabs_4" ><a href="#"><?php echo $this->__('Reviews'); ?></a></li>
                </ul>
                <div class="padder">
                    <div id="product_tabs_1_contents">
                        <?php echo $_product->getDescription(); ?>
                    </div>
                    <div id="product_tabs_2_contents">
                        <?php echo $_product->getInfo(); ?>
                    </div>
                    <div id="product_tabs_3_contents">
                        <?php echo $_product->getLegalDisclaimer(); ?>
                    </div>
                    <div id="product_tabs_4_contents">
                        <?php echo $this->getChildHtml('product_review'); ?>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
            //<![CDATA[
                //new Varien.Tabs('.tabs');
                jQuery(document).ready(function($) {
                    $(window).load(function(){
                        $('.tabs').each(function(){
                            idTab = $(this).children('.active').attr('id');
                            $(this).next('.padder').children().hide();
                            $(this).next('.padder').children('#'+idTab+'_contents').show();
                        });
                    });

                    $(window).resize(function() {
                        setTimeout(function() {
                            $('.tabs').each(function(){
                                idTab = $(this).children('.active').attr('id');
                                $(this).next('.padder').children().hide();
                                $(this).next('.padder').children('#'+idTab+'_contents').show();
                            });
                        },500);
                    });

                    $(document).on('click','.tabs > li',function() {
                        $(this).siblings().removeClass('active');
                        $(this).addClass('active');
                        idTab = $(this).attr('id');
                        $(this).parent().next('.padder').children().hide();
                        $(this).parent().next('.padder').children('#'+idTab+'_contents').show();
                        return false;
                    });
                });
            //]]>
            </script>
