<?php $category = $this->_getCategory() ?>
<?php $storeId = Mage::app()->getStore()->getId(); ?>
<?php if (sizeof($category) > 0) : ?>
<?php $this->setPriceTemplate('catalog/product/price_grid.phtml') ?>
<?php $_helper = $this->helper('catalog/output') ?>
<?php $_cHelper = $this->helper('icategory') ?>
<?php $_columnCount = $this->getColumnCount() ? $this->getColumnCount() : 4; ?>
<?php $suffix = md5(microtime() . mt_rand()) ?>
<div class="product-tab-container">
    <ul class="tabs">
        <?php $i = 0 ?>
        <?php foreach ($category as $_item) : ?>
            <?php if ($i == 0) : ?>
                <li id="product_tabs_<?php echo $_item->getId() ?>" class="active first">
                    <a href="#"><?php echo $_item->getName() ?></a></li>
            <?php else : ?>
                <li id="product_tabs_<?php echo $_item->getId() ?>">
                    <a href="#"><?php echo $_item->getName() ?></a></li>
            <?php endif ?>
            <?php $i ++ ?>
        <?php endforeach ?>
    </ul>
    <div class="padder">
        <?php foreach ($category as $_item) : ?>
            <div id="product_tabs_<?php echo $_item->getId() ?>_contents" class="product-content-inner">
                <?php $_collection = $this->_getCollection($_item) ?>
                <?php if ($_collection->count()): ?>
                    <div class="bx-container-controller product-tab-controller">
                        <span class="bx-prev bx-prev-<?php echo $suffix.'-'.$_item->getId(); ?>"></span>
                        <span class="bx-next bx-next-<?php echo $suffix.'-'.$_item->getId(); ?>"></span>
                    </div>
                    <div class="product-list-tab">
                        <ul id="product_tabs_<?php echo $_item->getId() ?>_slider" class="grid-column-<?php echo $_columnCount; ?> products-grid-slider bxslider bxslider-<?php echo $suffix.'-'.$_item->getId(); ?>">
                            <?php foreach ($_collection as $_product): ?>
                                <?php $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId()); ?>
                                <?php $s = $_cHelper->getSize($_product, 195, 145, 'small_image', 'width'); ?>
                                <li class="item">
                                    <div class="product-id">
                                        <span><?php echo $this->__('Item #') . $_product->getEntityId(); ?></span>
                                    </div>
                                    <div class="product-image-outer"><div class="product-image-inner">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($s->getWidth(), $s->getHeight()); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                                    </div></div>
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                    <div class="product-description">
                                        <?php if ($s = $_product->getShortDescription()):?>
                                            <div class="std"><?php echo $_helper->productAttribute($_product, $s, 'short_description') ?></div>
                                        <?php endif; ?>
                                    </div>
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                    <div class="actions">
                                        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="productAddToCartForm<?php echo $_product->getId(); ?>.submit(this)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                            <div class="qty-group">
                                                <input type="button" class="btn btn-qty-number btn-minus" value="-" />
                                                <input type="text" name="qty" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty validated-number" / ?>
                                                <input type="button" class="btn btn-qty-number btn-plus" value="+" />
                                            </div>
                                        </form>
                                    </div>
                                </li>
                                <script type="text/javascript">
                                //<![CDATA[
                                    var productAddToCartForm<?php echo $_product->getId(); ?> = new VarienForm('product_addtocart_form_<?php echo $_product->getId(); ?>');
                                //]]>
                                </script>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <script type="text/javascript">
                        //<![CDATA[
                        jQuery(document).ready(function($) {
                            $('.bxslider-<?php echo $suffix.'-'.$_item->getId(); ?>').bxSlider({
                                mode: 'horizontal',
                                speed: 500,
                                infiniteLoop: true,
                                auto: false,
                                pause: 4000,
                                moveSlides: 1,
                                slideMargin: 20,
                                slideWidth: 195,
                                minSlides: 1,
                                maxSlides: <?php echo $_columnCount; ?>,
                                nextSelector: '.bx-next-<?php echo $suffix.'-'.$_item->getId(); ?>',
                                prevSelector: '.bx-prev-<?php echo $suffix.'-'.$_item->getId(); ?>',
                                pager: false
                            });
                        });
                        //]]>
                        </script>
                <?php endif; ?>
            </div>
        <?php endforeach ?>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($) {
        $(window).load(function(){
            $('.tabs').each(function(){
                idTab = $(this).children('.active').attr('id');
                $(this).next('.padder').children().hide();
                $(this).next('.padder').children('#'+idTab+'_contents').show();
            });
        });

        $(window).resize(function() {
            setTimeout(function() {
                $('.tabs').each(function(){
                    idTab = $(this).children('.active').attr('id');
                    $(this).next('.padder').children().hide();
                    $(this).next('.padder').children('#'+idTab+'_contents').show();
                });
            },500);
        });

        $(document).on('click','.tabs > li',function() {
            $(this).siblings().removeClass('active');
            $(this).addClass('active');
            idTab = $(this).attr('id');
            $(this).parent().next('.padder').children().hide();
            $(this).parent().next('.padder').children('#'+idTab+'_contents').show();
            return false;
        });

        //slider

    });
//]]>
</script>
<?php endif ?>