        <div class="tb-right">
        <div class="sort-by">
            <label><?php echo $this->__('Sort By') ?></label>
            <select onchange="setLocation(this.value)" class="multi-select sort-by">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <?php /*<option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?> class="<?php echo $_key; ?>">
                    <?php echo $this->__($_order) ?>
                </option> */?>
                <?php 
                $html = '';
                if($_key == 'entity_id'){
                    $html .= '
                        <option value="'.$this->getOrderUrl($_key, 'asc').'"';
                    if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc') {
                        $html .= ' selected';
                    }
                    $html .= '>'.'Oldest'.'</option>';
                    $html .= '
                        <option value="'.$this->getOrderUrl($_key, 'desc').'"';
                    if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc') {
                        $html .= ' selected';
                    }
                    $html .= '>'.'Newest'.'</option>';
                }
                elseif($_key == 'name') {
                    $html .= '
                        <option value="'.$this->getOrderUrl($_key, 'asc').'"';
                        if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc') {
                            $html .= ' selected';
                        }
                        $html .= '>'.$_order.' (A-Z)'.'</option>';
                        $html .= '
                            <option value="'.$this->getOrderUrl($_key, 'desc').'"';
                        if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc') {
                            $html .= ' selected';
                        }
                    $html .= '>'.$_order.' (Z-A)'.'</option>';
                }
				elseif($_key == 'price') {
                    $html .= '
                        <option value="'.$this->getOrderUrl($_key, 'asc').'"';
                    if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc') {
                        $html .= ' selected';
                    }
                    $html .= '>'.$_order.' (Low - Hight)'.'</option>';
                                $html .= '
                    <option value="'.$this->getOrderUrl($_key, 'desc').'"';
                                if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc') {
                                    $html .= ' selected';
                                }
                    $html .= '>'.$_order.' (Hight-Low)'.'</option>';
                }
                elseif($_key == 'position') {
                    $html .= '
        				<option value="'.$this->getOrderUrl($_key, 'asc').'"';
                    if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc') {
                        $html .= ' selected';
                    }
        			$html .= '>'.$_order.' (Low - Hight)'.'</option>';
                    $html .= '
        				<option value="'.$this->getOrderUrl($_key, 'desc').'"';
                    if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc') {
                        $html .= ' selected';
                    }
        			$html .= '>'.$_order.' (Hight-Low)'.'</option>';
                }else{
                    $html .= '
                        <option value="'.$this->getOrderUrl($_key, 'asc').'"';
                        if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc') {
                            $html .= ' selected';
                        }
                    $html .= '>'.$_order.' (Low - Hight)'.'</option>';
	                $html .= '
	                    <option value="'.$this->getOrderUrl($_key, 'desc').'"';
                    if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc') {
		                $html .= ' selected';
                    }
                    $html .= '>'.$_order.' (Hight-Low)'.'</option>';
                }
                echo $html;
    			?>
            <?php endforeach; ?>
            </select>
        </div>
    </div>
    <?php endif; ?>
</div>
<?php endif ?>







<?php 
                $html = '';
                if($_key == 'entity_id'){
                    $html .= '
                        <option value="'.$this->getOrderUrl($_key, 'desc').'"';
                    if($this->isOrderCurrent($_key)) {
                        $html .= ' selected';
                    }
                    $html .= '>'.'New Arrivals'.'</option>';
                }
                elseif($_key == 'name') {
                    $html .= '
                        <option value="'.$this->getOrderUrl($_key, 'asc').'"';
                        if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc') {
                            $html .= ' selected';
                        }
                        $html .= '>'.$_order.' (A to Z)'.'</option>';
                        $html .= '
                            <option value="'.$this->getOrderUrl($_key, 'desc').'"';
                        if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc') {
                            $html .= ' selected';
                        }
                    $html .= '>'.$_order.' (Z to A)'.'</option>';
                }
                elseif($_key == 'price') {
                    $html .= '
                    <option value="'.$this->getOrderUrl($_key, 'desc').'"';
                    if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc') {
                        $html .= ' selected';
                    }
                    $html .= '>'.$_order.' (Highest to Lowest)'.'</option>';
                    $html .= '
                        <option value="'.$this->getOrderUrl($_key, 'asc').'"';
                    if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc') {
                        $html .= ' selected';
                    }
                    $html .= '>'.$_order.' (Lowest to Highest)'.'</option>';
                }
                else{
                    $html .= '
                        <option value="'.$this->getOrderUrl($_key, 'asc').'"';
                        if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc') {
                            $html .= ' selected';
                        }
                    $html .= '>'.$_order.' (Low - Hight)'.'</option>';
                    $html .= '
                        <option value="'.$this->getOrderUrl($_key, 'desc').'"';
                    if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc') {
                        $html .= ' selected';
                    }
                    $html .= '>'.$_order.' (Hight-Low)'.'</option>';
                }
                echo $html;
                ?>