version: '3'

services:
  ### nginx - web service
  nginx:
    restart: always
    image: nginx:1.13
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/site:/etc/nginx/conf.d
      # - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params.conf
      - ./code/static:/app/code/static
      - ./code/media:/app/code/media
    depends_on:
      - python
    # links:
    #   - python:python

  ### python django - program language
  python:
    restart: always
    build: .
    expose:
      - "8000"
    volumes:
      - ./code:/app/code
    environment:
      DEBUG: 'true'
    command: uwsgi --ini /app/uwsgi.ini
    # depends_on:
    #   - db
    # links:
    #   - db:db

  db:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - "3306:3306"
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'ricode'
    volumes:
      - ./mysqldata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

